name: Build and deploy main

env:
  AZURE_WEBAPP_NAME: jzdemoapi
  AZURE_FUNCTIONAPP_NAME: jzdemofunc
  
on:
  push:
    branches:
      - main 
    paths:
      - 'src/function/**'
      - 'src/webapi/**'

jobs:

  build-webapi:
    name: 'Build Web Api'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Publish
      run: dotnet publish --output './output/webapi/' './src/webapi/webapi.csproj'
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: webapi
        path: './output/webapi'

  build-function:
    name: 'Build Function'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore './src/function/function.csproj'
    - name: Build
      run: dotnet build --configuration Release --no-restore --output './output/function' './src/function/function.csproj'
    - name: Test
      run: dotnet test --no-restore --verbosity normal --output './output/function' './src/function/function.csproj'
    - name: Upload Artifact 
      uses: actions/upload-artifact@v2
      with:
        name: function
        path: './output/function'
    
  porter-build:

    runs-on: ubuntu-latest
    needs: [ build-function, build-webapi ]
    steps:
    - uses: actions/checkout@v1

    - name: Get application artifacts
      uses: actions/download-artifact@v2
      with:
        path: './output/'
    - name: Setup Porter
      uses: deislabs/porter-gh-action@v0.1.1
    - uses: azure/docker-login@v1
      name: Docker Login
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: printf
      run: |
        pwd
        ls -a 
        ls output
        ls src/arm

    - name: Porter Publish
      run: porter publish  

  deploy-webapi:
    name: Deploy Web Api
    runs-on: ubuntu-latest
    needs: build-webapi

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: webapi
        path: ./output/webapi

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure WebApp Action'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: './output/webapi'

  deploy-function:
    name: Deploy Function
    runs-on: ubuntu-latest
    needs: build-function

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: function
        path: './output/function'

    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: './output/function'